spring:
  mail:
    host: smtp.naver.com
    port: 465
    username: heodangreview@naver.com
    password: heodang2193
    properties:
      mail.smtp.auth: true
      mail.smtp.ssl.enable: true
      mail.smtp.ssl.trust: smtp.naver.com
      mail.smtp.starttls.enable: true